getUIParams <- function(cellBlock) {
  switch(cellBlock,
         "replext_t2_c1.1" = list(shiny::numericInput("M1", "Mean for the first group:", 5),
                                  shiny::numericInput("S1", "Standard deviation for the first group:", 1),
                                  shiny::numericInput("M2", "Mean for the second group:", 5),
                                  shiny::numericInput("S2", "Standard deviation for the second group:", 1),
                                  shiny::numericInput("Sk1", "Skew for the first group:", value = NA),
                                  shiny::numericInput("Sk2", "Skew for the second group:", value = NA),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "3,4,5,6,7,8,9,10,15"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "3,4,5,6,7,8,9,10,15"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t2_c1.2" = list(shiny::numericInput("M1", "Mean for the first group:", 5),
                                  shiny::numericInput("S1", "Standard deviation for the first group:", 1),
                                  shiny::numericInput("M2", "Mean for the second group:", 5),
                                  shiny::numericInput("S2", "Standard deviation for the second group:", 3),
                                  shiny::numericInput("Sk1", "Skew for the first group:", value = NA),
                                  shiny::numericInput("Sk2", "Skew for the second group:", value = NA),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "3,4,5,6,7,8,9,10,15"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "3,4,5,6,7,8,9,10,15"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t2_c2.1" = list(shiny::numericInput("M1", "Mean for the first group:", 5),
                                  shiny::numericInput("S1", "Standard deviation for the first group:", 1),
                                  shiny::numericInput("M2", "Mean for the second group:", 5),
                                  shiny::numericInput("S2", "Standard deviation for the second group:", 1),
                                  shiny::numericInput("Sk1", "Skew for the first group:", value = 0.8),
                                  shiny::numericInput("Sk2", "Skew for the second group:", value = 0.8),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "3,4,5,6,7,8,9,10,15"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "3,4,5,6,7,8,9,10,15"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t2_c2.2" = list(shiny::numericInput("M1", "Mean for the first group:", 5),
                                  shiny::numericInput("S1", "Standard deviation for the first group:", 1),
                                  shiny::numericInput("M2", "Mean for the second group:", 5),
                                  shiny::numericInput("S2", "Standard deviation for the second group:", 3),
                                  shiny::numericInput("Sk1", "Skew for the first group:", value = 0.8),
                                  shiny::numericInput("Sk2", "Skew for the second group:", value = 0.8),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "3,4,5,6,7,8,9,10,15"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "3,4,5,6,7,8,9,10,15"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t2_c3.1" = list(shiny::numericInput("M1", "Mean for the first group:", 5),
                                  shiny::numericInput("S1", "Standard deviation for the first group:", 1),
                                  shiny::numericInput("M2", "Mean for the second group:", 5),
                                  shiny::numericInput("S2", "Standard deviation for the second group:", 1),
                                  shiny::numericInput("Sk1", "Skew for the first group:", value = 0.8),
                                  shiny::numericInput("Sk2", "Skew for the second group:", value = 1),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "3,4,5,6,7,8,9,10,15"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "3,4,5,6,7,8,9,10,15"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t2_c3.2" = list(shiny::numericInput("M1", "Mean for the first group:", 5),
                                  shiny::numericInput("S1", "Standard deviation for the first group:", 1),
                                  shiny::numericInput("M2", "Mean for the second group:", 5),
                                  shiny::numericInput("S2", "Standard deviation for the second group:", 3),
                                  shiny::numericInput("Sk1", "Skew for the first group:", value = 0.8),
                                  shiny::numericInput("Sk2", "Skew for the second group:", value = 1),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "3,4,5,6,7,8,9,10,15"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "3,4,5,6,7,8,9,10,15"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t2_c4.1" = list(shiny::numericInput("M1", "Mean for the first group:", 5),
                                  shiny::numericInput("S1", "Standard deviation for the first group:", 1),
                                  shiny::numericInput("M2", "Mean for the second group:", 5),
                                  shiny::numericInput("S2", "Standard deviation for the second group:", 1),
                                  shiny::numericInput("Sk1", "Skew for the first group:", value = 0.8),
                                  shiny::numericInput("Sk2", "Skew for the second group:", value = 0.8),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "4,3,5,4,6,4,3,4,5,6"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "2,4,3,5,3,6,7,11,10,9"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t2_c4.2" = list(shiny::numericInput("M1", "Mean for the first group:", 5),
                                  shiny::numericInput("S1", "Standard deviation for the first group:", 1),
                                  shiny::numericInput("M2", "Mean for the second group:", 5),
                                  shiny::numericInput("S2", "Standard deviation for the second group:", 3),
                                  shiny::numericInput("Sk1", "Skew for the first group:", value = 0.8),
                                  shiny::numericInput("Sk2", "Skew for the second group:", value = 0.8),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "4,3,5,4,6,4,3,4,5,6"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "2,4,3,5,3,6,7,11,10,9"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t3_c1.1" = list(shiny::numericInput("M1", "Mean for the first group:", 5),
                                  shiny::numericInput("S1", "Standard deviation for the first group:", 1),
                                  shiny::numericInput("M2", "Mean for the second group:", 7),
                                  shiny::numericInput("S2", "Standard deviation for the second group:", 1),
                                  shiny::numericInput("Sk1", "Skew for the first group:", value = NA),
                                  shiny::numericInput("Sk2", "Skew for the second group:", value = NA),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "3,4,5,6,7,8,9,10,15,25,50,100"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "3,4,5,6,7,8,9,10,15,25,50,100"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t3_c1.2" = list(shiny::numericInput("M1", "Mean for the first group:", 5),
                                  shiny::numericInput("S1", "Standard deviation for the first group:", 1),
                                  shiny::numericInput("M2", "Mean for the second group:", 7),
                                  shiny::numericInput("S2", "Standard deviation for the second group:", 3),
                                  shiny::numericInput("Sk1", "Skew for the first group:", value = NA),
                                  shiny::numericInput("Sk2", "Skew for the second group:", value = NA),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "3,4,5,6,7,8,9,10,15,25,50,100"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "3,4,5,6,7,8,9,10,15,25,50,100"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t3_c2.1" = list(shiny::numericInput("M1", "Mean for the first group:", 5),
                                  shiny::numericInput("S1", "Standard deviation for the first group:", 1),
                                  shiny::numericInput("M2", "Mean for the second group:", 7),
                                  shiny::numericInput("S2", "Standard deviation for the second group:", 1),
                                  shiny::numericInput("Sk1", "Skew for the first group:", value = 0.8),
                                  shiny::numericInput("Sk2", "Skew for the second group:", value = 0.8),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "3,4,5,6,7,8,9,10,15,25,50,100"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "3,4,5,6,7,8,9,10,15,25,50,100"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t3_c2.2" = list(shiny::numericInput("M1", "Mean for the first group:", 5),
                                  shiny::numericInput("S1", "Standard deviation for the first group:", 1),
                                  shiny::numericInput("M2", "Mean for the second group:", 7),
                                  shiny::numericInput("S2", "Standard deviation for the second group:", 3),
                                  shiny::numericInput("Sk1", "Skew for the first group:", value = 0.8),
                                  shiny::numericInput("Sk2", "Skew for the second group:", value = 0.8),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "3,4,5,6,7,8,9,10,15,25,50,100"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "3,4,5,6,7,8,9,10,15,25,50,100"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t3_c3.1" = list(shiny::numericInput("M1", "Mean for the first group:", 5),
                                  shiny::numericInput("S1", "Standard deviation for the first group:", 1),
                                  shiny::numericInput("M2", "Mean for the second group:", 7),
                                  shiny::numericInput("S2", "Standard deviation for the second group:", 1),
                                  shiny::numericInput("Sk1", "Skew for the first group:", value = 0.8),
                                  shiny::numericInput("Sk2", "Skew for the second group:", value = 1),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "3,4,5,6,7,8,9,10,15,25,50,100"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "3,4,5,6,7,8,9,10,15,25,50,100"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t3_c3.2" = list(shiny::numericInput("M1", "Mean for the first group:", 5),
                                  shiny::numericInput("S1", "Standard deviation for the first group:", 1),
                                  shiny::numericInput("M2", "Mean for the second group:", 7),
                                  shiny::numericInput("S2", "Standard deviation for the second group:", 3),
                                  shiny::numericInput("Sk1", "Skew for the first group:", value = 0.8),
                                  shiny::numericInput("Sk2", "Skew for the second group:", value = 1),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "3,4,5,6,7,8,9,10,15,25,50,100"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "3,4,5,6,7,8,9,10,15,25,50,100"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t3_c4.1" = list(shiny::numericInput("M1", "Mean for the first group:", 5),
                                  shiny::numericInput("S1", "Standard deviation for the first group:", 1),
                                  shiny::numericInput("M2", "Mean for the second group:", 7),
                                  shiny::numericInput("S2", "Standard deviation for the second group:", 1),
                                  shiny::numericInput("Sk1", "Skew for the first group:", value = 0.8),
                                  shiny::numericInput("Sk2", "Skew for the second group:", value = 0.8),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "4,3,5,4,6,4"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "2,4,3,5,3,6"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t3_c4.2" = list(shiny::numericInput("M1", "Mean for the first group:", 5),
                                  shiny::numericInput("S1", "Standard deviation for the first group:", 1),
                                  shiny::numericInput("M2", "Mean for the second group:", 7),
                                  shiny::numericInput("S2", "Standard deviation for the second group:", 3),
                                  shiny::numericInput("Sk1", "Skew for the first group:", value = 0.8),
                                  shiny::numericInput("Sk2", "Skew for the second group:", value = 0.8),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "4,3,5,4,6,4"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "2,4,3,5,3,6"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t4_c1.1" = list(shiny::textInput("rdist", "Distribution type:", "rlnorm"),
                                  shiny::numericInput("par1_1", "meanlog Group 1:", 1),
                                  shiny::numericInput("par2_1", "sdlog Group1:", 0.6),
                                  shiny::numericInput("par1_2", "meanlog Group 2:", 2),
                                  shiny::numericInput("par2_2", "sdlog Group2:", 1),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "5,5,10"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "5,10,10"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t4_c2.1" = list(shiny::textInput("rdist", "Distribution type:", "rpois"),
                                  shiny::numericInput("par1_1", "lambda Group 1:", 5),
                                  #shiny::numericInput("par2_1", "not applicable", NA),
                                  shiny::numericInput("par1_2", "lambda Group 2:", 10),
                                  #shiny::numericInput("par2_2", "not applicable", NA),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "5,5,10"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "5,10,10"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t4_c3.1" = list(shiny::textInput("rdist", "Distribution type:", "rchisq"),
                                  shiny::numericInput("par1_1", "dof Group 1:", 1),
                                  shiny::numericInput("par2_1", "ncp Group 1", 0),
                                  shiny::numericInput("par1_2", "dof Group 2:", 6),
                                  shiny::numericInput("par2_2", "ncp Group 2", 0),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "5,5,10"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "5,10,10"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t4_c4.1" = list(shiny::textInput("rdist", "Distribution type:", "rlnorm"),
                                  shiny::numericInput("par1_1", "meanlog Group 1:", 1),
                                  shiny::numericInput("par2_1", "sdlog Group1:", 0.6),
                                  shiny::numericInput("par1_2", "meanlog Group 2:", 3),
                                  shiny::numericInput("par2_2", "sdlog Group2:", 4),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "5,5,10"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "5,10,10"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t4_c5.1" = list(shiny::textInput("rdist", "Distribution type:", "rcauchy"),
                                  shiny::numericInput("par1_1", "location Group 1:", 5),
                                  shiny::numericInput("par2_1", "scale Group1:", 2),
                                  shiny::numericInput("par1_2", "location Group 2:", 10),
                                  shiny::numericInput("par2_2", "scale Group2:", 4),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "5,5,10"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "5,10,10"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t4_c6.1" = list(shiny::textInput("rdist", "Distribution type:", "rchisq,rpois"),
                                  shiny::numericInput("par1_1", "dof Group 1:", 6),
                                  shiny::numericInput("par2_1", "ncp Group1:", 0),
                                  shiny::numericInput("par1_2", "lambda Group 2:", 10),
                                  #shiny::numericInput("par2_2", "scale Group2:", NA),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "5,5,10"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "5,10,10"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95)),
         "replext_t4_c7.1" = list(shiny::textInput("rdist", "Distribution type:", "rlnorm,rchisq"),
                                  shiny::numericInput("par1_1", "meanlog Group 1:", 1),
                                  shiny::numericInput("par2_1", "sdlog Group1:", 0.6),
                                  shiny::numericInput("par1_2", "dof Group 2:", 6),
                                  shiny::numericInput("par2_2", "ncp Group2:", 0),
                                  shiny::textInput("n1", "Sample sizes for the first group:", "5,5,10"),
                                  shiny::textInput("n2", "Sample sizes for the second group:", "5,10,10"),
                                  shiny::numericInput("n_simulations", "Number of simulation iterations:", 10000),
                                  shiny::numericInput("nboot", "Number of bootstrap iterations:", 1000),
                                  shiny::numericInput("conf.level", "Confidence level:", 0.95))
         )
}

runSimulation <- function(input) {
  # Helper functions for specific processing
  handle_null <- function(par_input = "") {
    if (is.na(par_input) || par_input == "") {
      return(NULL)
    } else {
      return(as.numeric(par_input))
    }
  }

  # Function for handling numeric vector input
  text_to_vector <- function(text_input) {
    as.numeric(unlist(strsplit(text_input, ",")))
  }

  # Function for handling character vector input
  text_to_char_vector <- function(text_input) {
    strsplit(trimws(text_input), ",")[[1]]
  }

  # Dynamically call the appropriate function based on the cell block prefix
  if (grepl("^replext_t2_", input$cellBlock)) {
    return(replext_t2_c1.1(M1 = input$M1, S1 = input$S1, M2 = input$M2, S2 = input$S2,
                           Sk1 = handle_null(input$Sk1), Sk2 = handle_null(input$Sk2),
                           n1 = text_to_vector(input$n1), n2 = text_to_vector(input$n2),
                           n_simulations = input$n_simulations, nboot = input$nboot,
                           conf.level = input$conf.level))
  } else if (grepl("^replext_t3_", input$cellBlock)) {
    return(replext_t3_c1.1(M1 = input$M1, S1 = input$S1, M2 = input$M2, S2 = input$S2,
                           Sk1 = handle_null(input$Sk1), Sk2 = handle_null(input$Sk2),
                           n1 = text_to_vector(input$n1), n2 = text_to_vector(input$n2),
                           n_simulations = input$n_simulations, nboot = input$nboot,
                           conf.level = input$conf.level))
  } else if (grepl("^replext_t4_", input$cellBlock)) {
    return(replext_t4_c1.1(rdist = text_to_char_vector(input$rdist), par1_1 = input$par1_1, par2_1 = handle_null(input$par2_1),
                           par1_2 = input$par1_2, par2_2 = handle_null(input$par2_2),
                           n1 = text_to_vector(input$n1),
                           n2 = text_to_vector(input$n2),
                           n_simulations = input$n_simulations, nboot = input$nboot,
                           conf.level = input$conf.level))
  } else{
    stop("Must select a supported cell block")
  }

}

